# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
  
- task: NodeTool@0
  inputs:
    versionSpec: '8.12.0'
  displayName: 'Install Node.js'
  
- script: which node
- script: node --version
  displayName: 'Node Version and path'

- script: |
    npm install sfdx-cli
- script: sfdx-cli --version
  displayName: 'sfdx install and version'
  
- script: sfdx force:auth:web:login -d -a "Hub Org"
  displayName: 'sfdx web login auth'
